export default {
  "enhance-nextjs-project": "Enhance a Next.js Project",
  "cicd-from-scratch": "CI/CD from Scratch",
  "security-audit": "Security Audit & Remediation",
  "interactive-chat": "Interactive Chat Sessions",
  "ci-debugging-and-analysis": "CI Debugging & Analysis",
  "custom-agents-and-modules": "Custom Agents & Modules",
  "advanced-plan-execution": "Advanced Plan Execution",
  "api-server-and-dashboard": "API Server & Dashboard",
  "provider-and-configuration": "Provider & Configuration",
  "model-aliases-and-thinking": "Model Aliases & Thinking Levels",
  "token-analytics-and-cost-control": "Token Analytics & Cost Control",
  "config-management-advanced": "Advanced Config Management",
  "observability-and-learning": "Observability & Learning",
};
